### PR TITLE
Add options to launch several server.

### PR DESCRIPTION
**Pull request by Mathieu-Geisert**

### CODE REVIEW

**Comment by nmansard** [comment]
Thanks for the patch. Could you motivate the need for this new feature? We can discuss it here and then add a synthesis to document the new method startCorbaServer.

**Comment by Mathieu-Geisert** [comment]
We did kind of the same modification for all corbaservers. That way, I can launch several times the same script on different servers without conflicts between names/scene/robot...
In the specific case of gepetto-viewer-corba, maybe it will be better (for computation time) to have only one server and to adjust hpp/pinocchio python scripts to easily handle different scenes.
However it was a lot easier for me to start a new fresh server as I do for the other corbaservers.

**Comment by Mathieu-Geisert** [comment]
We did kind of the same modification for all corbaservers. That way, I can launch several times the same script on different servers without conflicts between names/scene/robot...
In the specific case of gepetto-viewer-corba, maybe it will be better (for computation time) to have only one server and to adjust hpp/pinocchio python scripts to easily handle different scenes.
However it was a lot easier for me to start a new fresh server as I do for the other corbaservers.

**Comment by jmirabel** [comment]
I think this issue should not be solved here but rather in the software using the viewer.

**Pull request closed without merging**
