### PR TITLE
Python interface uses (x,y,z,w) convention for quaternions.

### PR DESCRIPTION
**Pull request by jmirabel**
Solves https://github.com/humanoid-path-planner/gepetto-viewer-corba/issues/38

### CODE REVIEW

**Comment by jmirabel** [comment]
This hasn't been deeply tested but there shouldn't be any places where it is problematic (in the C++ side)

**Comment by nmansard** [comment]
Ok. Thx. 
I think we should merge this when preparing a new version for GV, GVC, Pinocchio and the HPP suite, so that the patch and its propagation are applied at the same time. What do you think?

**Comment by jmirabel** [comment]
Yes, I don't think it is a very good idea to merge it in master right now. It's probably more suitable to merge it in devel and give some time to downstream software be updated.

**Comment by jcarpent** [comment]
Let's discussing all the consequence of this modification during next HPP meeting with everybody!

**Comment by jmirabel** [comment]
In HPP, there are two consequences:
- hpp-gepetto-viewer: very easy to handle (I think only one function)
- user script: no way to handle it.

**Comment by jcarpent** [comment]
For Pinocchio, it only affects the Python part and then, two functions. Normally, if the users'script are well done, they directly rely on these functions.

**Comment by jmirabel** [comment]
It seems there is not much effort to update other software.
Moreover, there are no HPP meeting during summer.

For this reasons, I think it is reasonable to move this change onto the devel branch and merge. We'll have to be carefully synchronising the next release. Anyone object ?

**Comment by florent-lamiraux** [comment]
We can make a HPP meeting tomorrow.

**Pull request closed without merging**
